### ISSUE TITLE
[PE-D][Tester E] Specifying student by matriculation number could be overly tedious

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14B-2/tp#193]
As a busy TA who cannot remember my students' matriculation numbers, I might find this program difficult to use. For instance, `attend-present m/A0296210X...`. If I make 1 typo, and the program reports an error, I might be frustrated as a TA.

For example, one of the commands which uses matriculation number is `attend-present`:
![image.png](https://raw.githubusercontent.com/sumomomomomo/ped/main/files/5b6bcb98-a76f-4478-82ad-02c106761879.png)
As a TA, I cannot tell from the error that I have mistyped a student's matriculation number.

Further, without a `find` command implemented, it could make it more tedious for the TA to scroll through every student.

Suggestion: allow the TA to use INDEX instead to target a student for commands that need matriculation number. 

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: sumomomomomo/ped#10

**Comment by FlyingDonkeys** [comment]
1. There is a ```person-find``` command actually.
2. Using index instead of matric number is a good improvement, since all indices are guaranteed to have a unique student. The issue would be translating from index number to matric number in the backend, then performing the relevant operations. This change will likely affect many commands, and fixing it would likely take too much time. Furthermore if the user cannot input matric number properly, its more of an inconvenience rather than a bug that breaks the app, so I would think it is ok to keep it as it is. Can be discussed though.

**Comment by accountexeregister** [comment]
Advantage of using index for 'person' commands: less tedious.
Disadvantage of using index for 'person' commands: not consistent with other command types (e.g. courses) which uses code.  

Any thoughts on which is better? Should we use index or matric number?
