### ISSUE TITLE
[PE-D][Tester E] Same person can be enrolled to multiple course + tutorial id combinations - UI does not reflect multiple enrolment

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14B-2/tp#209]
For instance, if Alex were enrolled in MA1521, T99 but I execute `enroll m/A1234567X c/MA1522 tut/T91`:
![image.png](https://raw.githubusercontent.com/sumomomomomo/ped/main/files/41e98c6a-9542-43f0-b97f-d47b9c3f2a9a.png)
^ command executed successfully.

![image.png](https://raw.githubusercontent.com/sumomomomomo/ped/main/files/0d74c0a9-a54b-4659-90e2-e9bd47b7739b.png)
^ I click on his attendance button, and see no sign of MA1522.

Further: `unenroll m/A1234567X c/MA1522 tut/T91` successfully executes, which seems to indicate a UI issue.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: sumomomomomo/ped#15

**Comment by FlyingDonkeys** [comment]
It was mentioned that __Students already enrolled in this course and tutorial cannot be enrolled again.__. Since you are enrolling Alex into MA1522 Tutorials 91 and 99, this is fine because Alex is enrolled in the same course but different tutorial slot. Although in practice, a Student probably shouldnt be in multiple tutorial slots.

**Comment by FlyingDonkeys** [comment]
We will allow combinations of same matric number, course code but different tutorial ids for now, unless we want to remove it and make (`MATRICULATION_NUMBER`, `COURSE_CODE`) the composite primary key.
